//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAutokauppa1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/WcfT6autoserver")]
    [System.SerializableAttribute()]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMalliIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMerkkiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HintaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MittarilukemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Moottorin_TilavuusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolttoaineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rekisteri_paivamaaraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VaritIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMalliID {
            get {
                return this.AutonMalliIDField;
            }
            set {
                if ((this.AutonMalliIDField.Equals(value) != true)) {
                    this.AutonMalliIDField = value;
                    this.RaisePropertyChanged("AutonMalliID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMerkkiID {
            get {
                return this.AutonMerkkiIDField;
            }
            set {
                if ((this.AutonMerkkiIDField.Equals(value) != true)) {
                    this.AutonMerkkiIDField = value;
                    this.RaisePropertyChanged("AutonMerkkiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hinta {
            get {
                return this.HintaField;
            }
            set {
                if ((this.HintaField.Equals(value) != true)) {
                    this.HintaField = value;
                    this.RaisePropertyChanged("Hinta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mittarilukema {
            get {
                return this.MittarilukemaField;
            }
            set {
                if ((this.MittarilukemaField.Equals(value) != true)) {
                    this.MittarilukemaField = value;
                    this.RaisePropertyChanged("Mittarilukema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Moottorin_Tilavuus {
            get {
                return this.Moottorin_TilavuusField;
            }
            set {
                if ((this.Moottorin_TilavuusField.Equals(value) != true)) {
                    this.Moottorin_TilavuusField = value;
                    this.RaisePropertyChanged("Moottorin_Tilavuus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolttoaineID {
            get {
                return this.PolttoaineIDField;
            }
            set {
                if ((this.PolttoaineIDField.Equals(value) != true)) {
                    this.PolttoaineIDField = value;
                    this.RaisePropertyChanged("PolttoaineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rekisteri_paivamaara {
            get {
                return this.Rekisteri_paivamaaraField;
            }
            set {
                if ((this.Rekisteri_paivamaaraField.Equals(value) != true)) {
                    this.Rekisteri_paivamaaraField = value;
                    this.RaisePropertyChanged("Rekisteri_paivamaara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VaritID {
            get {
                return this.VaritIDField;
            }
            set {
                if ((this.VaritIDField.Equals(value) != true)) {
                    this.VaritIDField = value;
                    this.RaisePropertyChanged("VaritID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="autonMerkit", Namespace="http://schemas.datacontract.org/2004/07/WcfT6autoserver")]
    [System.SerializableAttribute()]
    public partial class autonMerkit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerkkiNimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerkkiNimi {
            get {
                return this.MerkkiNimiField;
            }
            set {
                if ((object.ReferenceEquals(this.MerkkiNimiField, value) != true)) {
                    this.MerkkiNimiField = value;
                    this.RaisePropertyChanged("MerkkiNimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="autonMallit", Namespace="http://schemas.datacontract.org/2004/07/WcfT6autoserver")]
    [System.SerializableAttribute()]
    public partial class autonMallit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MalliNimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MerkkiIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MalliNimi {
            get {
                return this.MalliNimiField;
            }
            set {
                if ((object.ReferenceEquals(this.MalliNimiField, value) != true)) {
                    this.MalliNimiField = value;
                    this.RaisePropertyChanged("MalliNimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MerkkiId {
            get {
                return this.MerkkiIdField;
            }
            set {
                if ((this.MerkkiIdField.Equals(value) != true)) {
                    this.MerkkiIdField = value;
                    this.RaisePropertyChanged("MerkkiId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Varit", Namespace="http://schemas.datacontract.org/2004/07/WcfT6autoserver")]
    [System.SerializableAttribute()]
    public partial class Varit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Varin_nimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varin_nimi {
            get {
                return this.Varin_nimiField;
            }
            set {
                if ((object.ReferenceEquals(this.Varin_nimiField, value) != true)) {
                    this.Varin_nimiField = value;
                    this.RaisePropertyChanged("Varin_nimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Polttoaine", Namespace="http://schemas.datacontract.org/2004/07/WcfT6autoserver")]
    [System.SerializableAttribute()]
    public partial class Polttoaine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Polttoaineen_nimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polttoaineen_nimi {
            get {
                return this.Polttoaineen_nimiField;
            }
            set {
                if ((object.ReferenceEquals(this.Polttoaineen_nimiField, value) != true)) {
                    this.Polttoaineen_nimiField = value;
                    this.RaisePropertyChanged("Polttoaineen_nimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        bool TestDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        System.Threading.Tasks.Task<bool> TestDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveAuto", ReplyAction="http://tempuri.org/IService1/saveAutoResponse")]
        bool saveAuto(WcfAutokauppa1.ServiceReference1.Auto pirssi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveAuto", ReplyAction="http://tempuri.org/IService1/saveAutoResponse")]
        System.Threading.Tasks.Task<bool> saveAutoAsync(WcfAutokauppa1.ServiceReference1.Auto pirssi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllAutoMakers", ReplyAction="http://tempuri.org/IService1/getAllAutoMakersResponse")]
        WcfAutokauppa1.ServiceReference1.autonMerkit[] getAllAutoMakers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllAutoMakers", ReplyAction="http://tempuri.org/IService1/getAllAutoMakersResponse")]
        System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.autonMerkit[]> getAllAutoMakersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAutoModels", ReplyAction="http://tempuri.org/IService1/getAutoModelsResponse")]
        WcfAutokauppa1.ServiceReference1.autonMallit[] getAutoModels(int merkkiId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAutoModels", ReplyAction="http://tempuri.org/IService1/getAutoModelsResponse")]
        System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.autonMallit[]> getAutoModelsAsync(int merkkiId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarColors", ReplyAction="http://tempuri.org/IService1/GetCarColorsResponse")]
        WcfAutokauppa1.ServiceReference1.Varit[] GetCarColors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarColors", ReplyAction="http://tempuri.org/IService1/GetCarColorsResponse")]
        System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Varit[]> GetCarColorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarFuels", ReplyAction="http://tempuri.org/IService1/GetCarFuelsResponse")]
        WcfAutokauppa1.ServiceReference1.Polttoaine[] GetCarFuels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCarFuels", ReplyAction="http://tempuri.org/IService1/GetCarFuelsResponse")]
        System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Polttoaine[]> GetCarFuelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NextAuto", ReplyAction="http://tempuri.org/IService1/NextAutoResponse")]
        WcfAutokauppa1.ServiceReference1.Auto NextAuto(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NextAuto", ReplyAction="http://tempuri.org/IService1/NextAutoResponse")]
        System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Auto> NextAutoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrevAuto", ReplyAction="http://tempuri.org/IService1/PrevAutoResponse")]
        WcfAutokauppa1.ServiceReference1.Auto PrevAuto(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrevAuto", ReplyAction="http://tempuri.org/IService1/PrevAutoResponse")]
        System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Auto> PrevAutoAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfAutokauppa1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfAutokauppa1.ServiceReference1.IService1>, WcfAutokauppa1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TestDatabaseConnection() {
            return base.Channel.TestDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<bool> TestDatabaseConnectionAsync() {
            return base.Channel.TestDatabaseConnectionAsync();
        }
        
        public bool saveAuto(WcfAutokauppa1.ServiceReference1.Auto pirssi) {
            return base.Channel.saveAuto(pirssi);
        }
        
        public System.Threading.Tasks.Task<bool> saveAutoAsync(WcfAutokauppa1.ServiceReference1.Auto pirssi) {
            return base.Channel.saveAutoAsync(pirssi);
        }
        
        public WcfAutokauppa1.ServiceReference1.autonMerkit[] getAllAutoMakers() {
            return base.Channel.getAllAutoMakers();
        }
        
        public System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.autonMerkit[]> getAllAutoMakersAsync() {
            return base.Channel.getAllAutoMakersAsync();
        }
        
        public WcfAutokauppa1.ServiceReference1.autonMallit[] getAutoModels(int merkkiId) {
            return base.Channel.getAutoModels(merkkiId);
        }
        
        public System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.autonMallit[]> getAutoModelsAsync(int merkkiId) {
            return base.Channel.getAutoModelsAsync(merkkiId);
        }
        
        public WcfAutokauppa1.ServiceReference1.Varit[] GetCarColors() {
            return base.Channel.GetCarColors();
        }
        
        public System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Varit[]> GetCarColorsAsync() {
            return base.Channel.GetCarColorsAsync();
        }
        
        public WcfAutokauppa1.ServiceReference1.Polttoaine[] GetCarFuels() {
            return base.Channel.GetCarFuels();
        }
        
        public System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Polttoaine[]> GetCarFuelsAsync() {
            return base.Channel.GetCarFuelsAsync();
        }
        
        public WcfAutokauppa1.ServiceReference1.Auto NextAuto(int ID) {
            return base.Channel.NextAuto(ID);
        }
        
        public System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Auto> NextAutoAsync(int ID) {
            return base.Channel.NextAutoAsync(ID);
        }
        
        public WcfAutokauppa1.ServiceReference1.Auto PrevAuto(int ID) {
            return base.Channel.PrevAuto(ID);
        }
        
        public System.Threading.Tasks.Task<WcfAutokauppa1.ServiceReference1.Auto> PrevAutoAsync(int ID) {
            return base.Channel.PrevAutoAsync(ID);
        }
    }
}
